### ISSUE TITLE
[ERROR] Test 1: "Received - Mail Servers Flow" failed: 'OUTLOOK.COM'

### ISSUE THREAD

**Issue by scoudeville** [mgeeky/decode-spam-headers#1]
Hello,

It seems the analysis of mail server flow doesn't like when FQDN are written in an uppercase style.

Here is an example of a problematic run with --debug parameter (FQDN's and other domains was changed for anonymity reasons):

`./decode-spam-headers.py /tmp/headers --debug
[INFO] Analysing: /tmp/headers
[DEBUG] Extracted 0. Received
[DEBUG] Extracted 1. Received
[DEBUG] Extracted 2. Received
[DEBUG] Extracted 3. Authentication-Results
[DEBUG] Extracted 4. Received-SPF
[DEBUG] Extracted 5. Received
[DEBUG] Extracted 6. Received
[DEBUG] Extracted 7. DKIM-Signature
[DEBUG] Extracted 8. To
[DEBUG] Extracted 9. Subject
[DEBUG] Extracted 10. Date
[DEBUG] Extracted 11. From
[DEBUG] Extracted 12. Message-ID
[DEBUG] Extracted 13. X-Mailer
[DEBUG] Extracted 14. MIME-Version
[DEBUG] Extracted 15. Content-Type
[DEBUG] Extracted 16. Content-Transfer-Encoding
[DEBUG] Extracted 17. Return-Path
[DEBUG] Extracted 18. X-MS-Exchange-Organization-ExpirationStartTime
[DEBUG] Extracted 19. X-MS-Exchange-Organization-ExpirationStartTimeReason
[DEBUG] Extracted 20. X-MS-Exchange-Organization-ExpirationInterval
[DEBUG] Extracted 21. X-MS-Exchange-Organization-ExpirationIntervalReason
[DEBUG] Extracted 22. X-MS-Exchange-Organization-Network-Message-Id
[DEBUG] Extracted 23. X-EOPAttributedMessage
[DEBUG] Extracted 24. X-EOPTenantAttributedMessage
[DEBUG] Extracted 25. X-MS-Exchange-Organization-MessageDirectionality
[DEBUG] Extracted 26. X-MS-PublicTrafficType
[DEBUG] Extracted 27. X-MS-Exchange-Organization-AuthSource
[DEBUG] Extracted 28. X-MS-Exchange-Organization-AuthAs
[DEBUG] Extracted 29. X-MS-Office365-Filtering-Correlation-Id
[DEBUG] Extracted 30. X-MS-TrafficTypeDiagnostic
[DEBUG] Extracted 31. X-MS-Oob-TLC-OOBClassifiers
[DEBUG] Extracted 32. X-MS-Exchange-Organization-SCL
[DEBUG] Extracted 33. X-Forefront-Antispam-Report
[DEBUG] Extracted 34. X-Microsoft-Antispam
[DEBUG] Extracted 35. X-MS-Exchange-CrossTenant-OriginalArrivalTime
[DEBUG] Extracted 36. X-MS-Exchange-CrossTenant-Network-Message-Id
[DEBUG] Extracted 37. X-MS-Exchange-CrossTenant-Id
[DEBUG] Extracted 38. X-MS-Exchange-CrossTenant-AuthSource
[DEBUG] Extracted 39. X-MS-Exchange-CrossTenant-AuthAs
[DEBUG] Extracted 40. X-MS-Exchange-CrossTenant-FromEntityHeader
[DEBUG] Extracted 41. X-MS-Exchange-Transport-CrossTenantHeadersStamped
[DEBUG] Extracted 42. X-MS-Exchange-Transport-EndToEndLatency
[DEBUG] Extracted 43. X-MS-Exchange-Processed-By-BccFoldering
[DEBUG] Extracted 44. X-Microsoft-Antispam-Mailbox-Delivery
[DEBUG] Extracted 45. X-Microsoft-Antispam-Message-Info
[INFO] Analysing 46 headers...
[DEBUG] Running test 1: "Received - Mail Servers Flow"...
[DEBUG] gethostbyaddr("1.2.3.4")...
[DEBUG] Cached gethostbyaddr("1.2.3.4") = "www.myhost.fr"
[DEBUG] gethostbyname("myhost.fr")...
[DEBUG] Cached gethostbyname("myhost.fr") = "1.2.3.4"
[DEBUG] Parsed Received header:
{
    "host": "www.myhost.fr",
    "host2": "www.myhost.fr",
    "ip": "1.2.3.4",
    "timestamp": "2021-11-08 18:12:31+00:00",
    "ver": "15.20.4669.10",
    "with": "Microsoft SMTP Server",
    "extra": [
        "version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    ],
    "num": 2,
    "parsed": {
        "from": "www.myhost.fr (1.2.3.4)",
        "by": "MR2FRA01FT016.mail.protection.outlook.com (10.152.50.130)",
        "with": "Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)",
        "id": "15.20.4669.10",
        "via": "Frontend Transport"
    },
    "_raw": "from www.myhost.fr (1.2.3.4) by MR2FRA01FT016.mail.protection.outlook.com (10.152.50.130) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4669.10 via Frontend Transport; Mon, 8 Nov 2021 18:12:31 +0000",
    "by": "MR2FRA01FT016.mail.protection.outlook.com",
    "id": "15.20.4669.10",
    "via": "Frontend Transport"
}
[DEBUG] gethostbyname("outlook.com")...
[DEBUG] Cached gethostbyname("outlook.com") = "40.97.164.146"
[DEBUG] Parsed Received header:
{
    "host": "MR2FRA01FT016.eop-fra01.prod.protection.outlook.com",
    "host2": "2603:10a6:20b:46d:cafe::14",
    "ip": "",
    "timestamp": "2021-11-08 18:12:32+00:00",
    "ver": "15.20.4669.11",
    "with": "Microsoft SMTP Server",
    "extra": [
        "2603:10a6:20b:46d::21",
        "version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    ],
    "num": 3,
    "parsed": {
        "from": "MR2FRA01FT016.eop-fra01.prod.protection.outlook.com (2603:10a6:20b:46d:cafe::14)",
        "by": "AS9P194CA0007.outlook.office365.com (2603:10a6:20b:46d::21)",
        "with": "Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)",
        "id": "15.20.4669.11",
        "via": "Frontend Transport"
    },
    "_raw": "from MR2FRA01FT016.eop-fra01.prod.protection.outlook.com (2603:10a6:20b:46d:cafe::14) by AS9P194CA0007.outlook.office365.com (2603:10a6:20b:46d::21) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4669.11 via Frontend Transport; Mon, 8 Nov 2021 18:12:32 +0000",
    "by": "AS9P194CA0007.outlook.office365.com",
    "id": "15.20.4669.11",
    "via": "Frontend Transport"
}
[DEBUG] gethostbyname("MR2FRA01FT016.eop-fra01.prod.protection.outlook.com")...
[DEBUG] Returning cached gethostbyname entry for: "OUTLOOK.COM"
[ERROR] Test 1: "Received - Mail Servers Flow" failed: 'OUTLOOK.COM' . Use --debug to show entire stack trace.
Traceback (most recent call last):
  File "./decode-spam-headers.py", line 6323, in <module>
    main(sys.argv)
  File "./decode-spam-headers.py", line 6303, in main
    out = an.parse(text)
  File "./decode-spam-headers.py", line 2021, in parse
    self.results[testName] = testFunc()
  File "./decode-spam-headers.py", line 4751, in testReceived
    obj = self.parseReceived(r, numReceived)
  File "./decode-spam-headers.py", line 4681, in parseReceived
    res = SMTPHeadersAnalysis.gethostbyname(f'{tldextracted.domain}.{tldextracted.suffix}')
  File "./decode-spam-headers.py", line 1821, in gethostbyname
    return SMTPHeadersAnalysis.resolved[name]
KeyError: 'OUTLOOK.COM'`

**Comment by mgeeky** [comment]
Hi! 

Thanks for opening this issue. 
Currently I'm on the vacation so I'll address it after I get back, which in about a month. 

Regards,
Mariusz.

**Comment by mgeeky** [comment]
Hi, I've had a few spare minutes and was able to jump onto my laptop for a second to fix this one. Could you please have a look whether the latest commit addresses this issue?

Best regards,
Mariusz.

**Comment by mgeeky** [comment]
Closing due to no follow-up. Please feel free to reopen the issue if you still experience these effects.
