### ISSUE TITLE
Office365 anti-spam rules: empiric tests led to decoding of two rules (42882007 and 78352004)

### ISSUE THREAD

**Issue by ipSlav** [mgeeky/decode-spam-headers#15]
Hi there,
While performing some empiric tests during an engagement, abusing `MS Direct Sender` for spoofing purposes, I noticed that (while using the exact same email pretext) the antispam rules 42882007 and 78352004 are matched when a `replyTo` address is missing. In this context this has been confirmed and easily fixed by adding the `-ReplyTo ` flag while sending the email from Azure CloudShell with the `Send-MailMessage` command.

**Comment by mgeeky** [comment]
Hi @ipSlav, that sounds like a terrific finding! How would you propose to name these two rules? :)

**Comment by mgeeky** [comment]
Landed now :) Sorry it took me so long! 

Once again thank you for terrific finding! :)
