### ISSUE TITLE
'utf-8' codec can't decode byte 0x8e

### ISSUE THREAD

**Issue by Nanparam** [mgeeky/decode-spam-headers#3]
I got following error when try to run with --decode-all option

←[38m[ERROR] ←[0m←[31mTest 29: "X-IronPort-Anti-Spam-Result" failed: 'utf-8' codec can't decode byte 0x8e in position 5: invalid start byte . Use --debug to show entire stack trace.←[0m
←[38m[ERROR] ←[0m←[31mTest 88: "IronPort-Data" failed: 'utf-8' codec can't decode byte 0xde in position 3: invalid continuation byte . Use --debug to show entire stack trace.←[0m
←[38m[ERROR] ←[0m←[31mTest 89: "IronPort-HdrOrder" failed: Invalid base64-encoded string: number of data characters (369) cannot be 1 more than a multiple of 4 . Use --debug to show entire stack trace.←[0m

**Comment by sauky** [comment]
Additional info while in debug mode catch in line 1783

 line 1783, in safeBase64Decode
    out = out.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 5: invalid start byte

**Comment by mgeeky** [comment]
Thanks for the bug report! I'll address it as soon as I get back from my holidays. Hopefully in ten days.

Regards,
M.

**Comment by mgeeky** [comment]
Hi @Nanparam, I've just submitted commit [02fb5a](https://github.com/mgeeky/decode-spam-headers/commit/02fb5aafe30ff40b252a27eda4f189c3e4911c70) that hopefully addresses your issue.

Could you please attempt to run the script again on the same headers as previously?
If the problem remains, I'd appreciate if you provided me with an anonymised headers for troubleshooting.

Regards,
Mariusz.

**Comment by mgeeky** [comment]
Closing due to no further comms. Feel free to re-open if you think problem remains!

**Comment by Snowman-25** [comment]
Re-Opening this because I have a very similar problem:
Header has the following To-Field
`To: =?iso-8859-1?Q?H=E4cker=2C_Henrik?= <h.haecker@DOMAIN>`

ERROR-Output from running the script with --debug:
```
[DEBUG] Running test 1: "Received - Mail Servers Flow"...
[ERROR] Test 1: "Received - Mail Servers Flow" failed: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte . Use --debug to show entire stack trace.
Traceback (most recent call last):
  File "decode-spam-headers.py", line 6439, in <module>
    main(sys.argv)
  File "decode-spam-headers.py", line 6419, in main
    out = an.parse(text)
  File "decode-spam-headers.py", line 2032, in parse
    self.results[testName] = testFunc()
  File "decode-spam-headers.py", line 4844, in testReceived
    (n2, h2, v2) = self.getHeader('To')
  File "decode-spam-headers.py", line 1894, in getHeader
    v1d = v1d.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
```
UTF-8 0xe4 should be this character: ä

**Comment by mgeeky** [comment]
Thank you @Snowman-25 for re-opening this one. 
I've addressed your issue - hopefully in other places besides the one reported.

Please do let me know if problem remains in the most recent version (the one with commit [45c7c2d](https://github.com/mgeeky/decode-spam-headers/commit/45c7c2d04058930b842dd197a9c7ac0c1e86a44b) ).

Regards,
Mariusz.

**Comment by Snowman-25** [comment]
Hey @mgeeky,

now it dies with the following message, regardless of --debug or not:

```
]$ python decode-spam-headers.py -a -r --debug spam-headers.txt
  File "decode-spam-headers.py", line 236
    return f'__COLOR_{c}__|{s}|__END_COLOR__'
                                            ^
SyntaxError: invalid syntax
```

Kind Regards,
Snowman-25

**Comment by mgeeky** [comment]
Hi @Snowman-25 , I never touched this fragment. Are you sure your `]$ python ` is running on version 3?

**Comment by Snowman-25** [comment]
> Are you sure your `]$ python ` is running on version 3?

You're right. That one was on me. Didn't activate the correct environment. Sorry!
The script doesn't crash now. But it does not print the character at all, which is unsatisfactory.
![grafik](https://user-images.githubusercontent.com/16033548/161256107-9f9f79dd-9a4f-484d-b4c2-b55e07571d11.png)
I imagine a name with asian script would just be completely blank.
