### ISSUE TITLE
X-Authenticated-Sender header

### ISSUE THREAD

**Issue by HenkPoley** [mgeeky/decode-spam-headers#4]
The X-Authenticated-Sender header might be interesting to display. It's syntax is like:
```
X-Authenticated-Sender: name@example.com
```

It appears to show the 'real' sender (mailserver account of sender) if the From: address is overridden to something else in the senders mail client.

---

This ticket used to read something different. In the end it was a customer who tried to send mail as us, from his ISP mailserver. Which is understandably blocked by Gmail. Sorry for the confusion. The header is still interesting.

**Comment by mgeeky** [comment]
Great, I'll add it given a free minute! Thanks Henk :)

**Comment by mgeeky** [comment]
Got it:

```
-----------------------------------------
(3) Test: The Real Sender - via Authenticated-Sender

HEADER:
    X-Authenticated-Sender

VALUE:
    name@example.com

ANALYSIS:

- This user has authenticated to the mail server to send that e-mail:
        - name@example.com

        - Mismatch with From header!
                - Authenticated user is not the same as declared in From header:

                        - Authenticated as:     name@example.com
                        - Sent e-mail as:       test@test.com
```

Thanks, closing it now :)

**Comment by HenkPoley** [comment]
Of course all of this can be forged. But I think proper language about that might get unintelligible.

**Comment by mgeeky** [comment]
Hmmm, so how do you propose to change the description or parsing logic @HenkPoley ?

**Comment by HenkPoley** [comment]
Another one of these sender's IP headers:

```
x-originating-ip: [102.89.3.149]
```
