### ISSUE TITLE
Test 17: "Domain Impersonation" failed: 'NoneType' object has no attribute 'group' . Use --debug to show entire stack trace.

### ISSUE THREAD

**Issue by poiu1235** [mgeeky/decode-spam-headers#6]
HI, first the tool is really very very useful.
But every time i run this script, it have an error on the top line.
"[ERROR] Test 17: "Domain Impersonation" failed: 'NoneType' object has no attribute 'group' . Use --debug to show entire stack trace."

maybe the test17 have some trouble.

by the way, thanks for your contribution.
Is there some advance tools that can resolve the MS outlook anti-spam header?
I want to know why my email judge into junk folder.
could you please provide some useful information to deal with it?

**Comment by mgeeky** [comment]
Hi @poiu1235 ,

Thanks for a kind comment. Can you please deliver me more details on the stack trace being thrown or anonymized input file that raises that exception? That would help be nail it down.

Regards,
Mariusz.

**Comment by poiu1235** [comment]
the header error is [ERROR] Test 17: "Domain Impersonation" failed: 'NoneType' object has no attribute 'group' . Use --debug to show entire stack trace.

**Comment by poiu1235** [comment]
awesome, this commit solve the problem.
thank you.

By the way, Friend,  do you have some advance tools that can explain the MS outlook anti-spam header?


> I've attempted to somewhat blindly your issue. Not sure whether it really nailed it so please do let me know.
> 
> This commit addresses this issue [09938b](https://github.com/mgeeky/decode-spam-headers/commit/09938b2bf3b4c55127be283d5010da160ccb58f0).
> 
> Regards, Mariusz

**Comment by mgeeky** [comment]
Glad it helped you. Unfortunately this header is opaque and there is not much documented on its contents so I'm not able to give more insight into what it contains. This tool attempts to extract as much as I was able to comprehend during my research sessions. Some of the rules could be deduced based on inputs provided to MS mail servers but that would be about it.
